frontend:
  extends:
    file: common.yml
    service: app
  command: frontend
  links:
    - kafka:kafka
api:
  extends:
    file: common.yml
    service: app
  command: api
  links:
    - kafka:kafka
worker:
  extends:
    file: common.yml
    service: app
  command: worker
  links:
    - kafka:kafka
scheduler:
  extends:
    file: common.yml
    service: app
  command: scheduler
  links:
    - kafka:kafka
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_CREATE_TOPICS: "imperium:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181"
